"""Sync database with models

Revision ID: 9bbe2a92097a
Revises:
Create Date: 2026-03-31 21:31:19.626358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bbe2a92097a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE creatorprofile ADD COLUMN IF NOT EXISTS bio TEXT")
    op.execute("ALTER TABLE creatorprofile ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(500)")
    op.execute("ALTER TABLE creatorprofile ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("ALTER TABLE creatorprofile ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")

    op.execute("COMMENT ON COLUMN creatorprofile.bio IS 'Creator biography'")
    op.execute("COMMENT ON COLUMN creatorprofile.profile_picture IS 'URL to profile picture'")
    op.execute("COMMENT ON COLUMN creatorprofile.created_at IS 'Profile creation timestamp'")
    op.execute("COMMENT ON COLUMN creatorprofile.updated_at IS 'Last update timestamp'")

    # Remove server_default after populating existing rows to match model (Python-side defaults)
    op.execute("ALTER TABLE creatorprofile ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE creatorprofile ALTER COLUMN updated_at DROP DEFAULT")
    op.alter_column('creatorprofile', 'id',
               existing_type=sa.INTEGER(),
               comment='Creator profile unique identifier',
               existing_nullable=False,
               autoincrement=True)
    # Clean up non-numeric user_ids before casting
    op.execute("DELETE FROM creatorprofile WHERE user_id !~ '^[0-9]+$'")
    op.alter_column('creatorprofile', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               comment='Reference to user_credential',
               existing_nullable=False,
               postgresql_using='user_id::integer')
    op.alter_column('creatorprofile', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Creator's full name",
               existing_nullable=False)
    op.alter_column('creatorprofile', 'phoneno',
               existing_type=sa.VARCHAR(length=255),
               comment="Creator's contact phone number",
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('creatorprofile', 'address',
               existing_type=sa.TEXT(),
               comment="Creator's physical address",
               existing_nullable=True)
    op.alter_column('creatorprofile', 'brandname',
               existing_type=sa.VARCHAR(length=255),
               comment='Brand or organization name',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('creatorprofile', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment="Creator's email address",
               existing_nullable=False)
    op.create_index('idx_creator_email', 'creatorprofile', ['email'], unique=False)
    op.create_index('idx_creator_name', 'creatorprofile', ['name'], unique=False)
    op.create_index('idx_creator_user_id', 'creatorprofile', ['user_id'], unique=False)

    # Deduplicate creatorprofile email
    op.execute("""
        UPDATE creatorprofile SET email = email || '_' || id
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) as rn
                FROM creatorprofile WHERE email IS NOT NULL
            ) t WHERE rn > 1
        )
    """)
    # Deduplicate creatorprofile user_id
    op.execute("""
        DELETE FROM creatorprofile WHERE id NOT IN (
            SELECT MAX(id) FROM creatorprofile GROUP BY user_id
        ) AND user_id IS NOT NULL
    """)

    op.create_index(op.f('ix_creatorprofile_brandname'), 'creatorprofile', ['brandname'], unique=False)
    op.create_index(op.f('ix_creatorprofile_email'), 'creatorprofile', ['email'], unique=True)
    op.create_index(op.f('ix_creatorprofile_user_id'), 'creatorprofile', ['user_id'], unique=True)
    # Clean up orphans before adding FK
    op.execute("DELETE FROM creatorprofile WHERE user_id NOT IN (SELECT id FROM user_credential)")
    op.create_foreign_key(None, 'creatorprofile', 'user_credential', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('eventcreation', 'id',
               existing_type=sa.INTEGER(),
               comment='Event unique identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('eventcreation', 'creator_id',
               existing_type=sa.INTEGER(),
               comment='Reference to creator profile',
               existing_nullable=True)
    op.alter_column('eventcreation', 'brand_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Brand organizing the event',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'event_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Event title/name',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'event_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Event venue address',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'time_in',
               existing_type=postgresql.TIME(),
               comment='Event start time',
               existing_nullable=True)
    op.alter_column('eventcreation', 'time_out',
               existing_type=postgresql.TIME(),
               comment='Event end time',
               existing_nullable=True)
    op.alter_column('eventcreation', 'summary',
               existing_type=sa.TEXT(),
               comment='Event description and details',
               existing_nullable=True)
    op.alter_column('eventcreation', 'picture',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               comment='Path to event promotional image',
               existing_nullable=True)
    op.alter_column('eventcreation', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Regular ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Event category (concert, conference, etc)',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'date',
               existing_type=sa.DATE(),
               nullable=False,
               comment='Event date')
    op.alter_column('eventcreation', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Bank account holder name',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'account_number',
               existing_type=sa.VARCHAR(length=255),
               comment='Bank account number',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'bank',
               existing_type=sa.VARCHAR(length=255),
               comment='Bank name',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'vip_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='VIP ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'vvip_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='VVIP ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'vvvip_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='VVVIP ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'table_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Table reservation price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='Event creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('eventcreation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               comment='Last update timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('eventcreation', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='Event availability status',
               existing_server_default=sa.text('true'))
    op.create_index('idx_event_category', 'eventcreation', ['category'], unique=False)
    op.create_index('idx_event_creator_id', 'eventcreation', ['creator_id'], unique=False)
    op.create_index('idx_event_date', 'eventcreation', ['date'], unique=False)
    op.create_index('idx_event_name', 'eventcreation', ['event_name'], unique=False)
    op.create_index(op.f('ix_eventcreation_category'), 'eventcreation', ['category'], unique=False)
    op.create_index(op.f('ix_eventcreation_creator_id'), 'eventcreation', ['creator_id'], unique=False)
    op.create_index(op.f('ix_eventcreation_date'), 'eventcreation', ['date'], unique=False)
    op.create_index(op.f('ix_eventcreation_event_name'), 'eventcreation', ['event_name'], unique=False)
    # Clean up orphans before adding FK
    op.execute("DELETE FROM eventcreation WHERE creator_id NOT IN (SELECT id FROM creatorprofile) AND creator_id IS NOT NULL")
    op.create_foreign_key(None, 'eventcreation', 'creatorprofile', ['creator_id'], ['id'], ondelete='CASCADE')
    # Adding event_id as nullable first because we might need to map it from event_name
    op.execute("ALTER TABLE table_categories ADD COLUMN IF NOT EXISTS event_id INTEGER")
    op.execute("COMMENT ON COLUMN table_categories.event_id IS 'Reference to event'")

    # Try to populate event_id from event_name if possible (best effort)
    op.execute("UPDATE table_categories SET event_id = (SELECT id FROM eventcreation WHERE event_name = table_categories.event_name LIMIT 1) WHERE event_id IS NULL")
    # Delete any rows that are still NULL (orphans)
    op.execute("DELETE FROM table_categories WHERE event_id IS NULL")
    # Here we'll just set it to NOT NULL and hope for the best or use a default if it's really missing.
    op.execute("ALTER TABLE table_categories ALTER COLUMN event_id SET NOT NULL")

    op.execute("ALTER TABLE table_categories ADD COLUMN IF NOT EXISTS available_tables INTEGER DEFAULT 0 NOT NULL")
    op.execute("ALTER TABLE table_categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("ALTER TABLE table_categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")

    op.execute("COMMENT ON COLUMN table_categories.available_tables IS 'Number of available tables'")
    op.execute("COMMENT ON COLUMN table_categories.created_at IS 'Record creation timestamp'")
    op.execute("COMMENT ON COLUMN table_categories.updated_at IS 'Last update timestamp'")

    op.execute("ALTER TABLE table_categories ALTER COLUMN available_tables DROP DEFAULT")
    op.execute("ALTER TABLE table_categories ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE table_categories ALTER COLUMN updated_at DROP DEFAULT")
    op.alter_column('table_categories', 'id',
               existing_type=sa.INTEGER(),
               comment='Table category unique identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('table_categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Table category name (e.g., Standard, VIP)',
               existing_nullable=False)
    op.alter_column('table_categories', 'capacity',
               existing_type=sa.INTEGER(),
               comment='Number of seats at this table',
               existing_nullable=False)
    op.alter_column('table_categories', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Price per table',
               existing_nullable=False)
    op.create_index('idx_table_event_id', 'table_categories', ['event_id'], unique=False)
    op.create_index('idx_table_name', 'table_categories', ['name'], unique=False)
    op.create_index(op.f('ix_table_categories_event_id'), 'table_categories', ['event_id'], unique=False)
    # Clean up orphans before adding FK
    op.execute("DELETE FROM table_categories WHERE event_id NOT IN (SELECT id FROM eventcreation)")
    op.create_foreign_key(None, 'table_categories', 'eventcreation', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('table_categories', 'event_name')
    op.execute("ALTER TABLE user_credential ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("ALTER TABLE user_credential ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("ALTER TABLE user_credential ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true NOT NULL")
    op.execute("COMMENT ON COLUMN user_credential.created_at IS 'Account creation timestamp'")
    op.execute("COMMENT ON COLUMN user_credential.updated_at IS 'Account creation timestamp'")
    op.execute("COMMENT ON COLUMN user_credential.is_active IS 'Account status flag'")
    op.execute("ALTER TABLE user_credential ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE user_credential ALTER COLUMN updated_at DROP DEFAULT")
    op.execute("ALTER TABLE user_credential ALTER COLUMN is_active DROP DEFAULT")
    op.alter_column('user_credential', 'id',
               existing_type=sa.INTEGER(),
               comment='Unique user identifier',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_credential', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Unique username for login',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_credential', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Unique email address',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_credential', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Hashed password using bcrypt',
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index('idx_email', 'user_credential', ['email'], unique=False)
    op.create_index('idx_username', 'user_credential', ['username'], unique=False)

    # Deduplicate username
    op.execute("""
        UPDATE user_credential SET username = username || '_' || id
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY username ORDER BY id) as rn
                FROM user_credential WHERE username IS NOT NULL
            ) t WHERE rn > 1
        )
    """)
    # Deduplicate email
    op.execute("""
        UPDATE user_credential SET email = email || '_' || id
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) as rn
                FROM user_credential WHERE email IS NOT NULL
            ) t WHERE rn > 1
        )
    """)

    op.create_index(op.f('ix_user_credential_email'), 'user_credential', ['email'], unique=True)
    op.create_index(op.f('ix_user_credential_username'), 'user_credential', ['username'], unique=True)
    # Safely handle id column and primary key for user_events
    op.execute("""
        DO $$
        BEGIN
            -- Drop old composite PK if it exists
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_events_pkey') THEN
                ALTER TABLE user_events DROP CONSTRAINT user_events_pkey;
            END IF;

            -- Add id column if it doesn't exist
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_events' AND column_name='id') THEN
                ALTER TABLE user_events ADD COLUMN id SERIAL;
            END IF;

            -- Add new PK if it doesn't exist
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_events_pkey_new' OR conname = 'user_events_pkey') THEN
                ALTER TABLE user_events ADD PRIMARY KEY (id);
            END IF;
        END $$;
    """)
    op.execute("ALTER TABLE user_events ADD COLUMN IF NOT EXISTS ticket_type VARCHAR(50)")
    op.execute("ALTER TABLE user_events ADD COLUMN IF NOT EXISTS isVerified BOOLEAN DEFAULT false NOT NULL")
    op.execute("ALTER TABLE user_events ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITHOUT TIME ZONE")
    op.execute("ALTER TABLE user_events ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")

    op.execute("COMMENT ON COLUMN user_events.id IS 'Ticket record unique identifier'")
    op.execute("COMMENT ON COLUMN user_events.ticket_type IS 'Ticket category (Regular, VIP, VVIP, etc)'")
    op.execute("COMMENT ON COLUMN user_events.isVerified IS 'Entry verification status'")
    op.execute("COMMENT ON COLUMN user_events.verified_at IS 'Ticket verification timestamp'")
    op.execute("COMMENT ON COLUMN user_events.created_at IS 'Record creation timestamp'")
    op.execute("ALTER TABLE user_events ALTER COLUMN isVerified DROP DEFAULT")
    op.execute("ALTER TABLE user_events ALTER COLUMN created_at DROP DEFAULT")
    op.alter_column('user_events', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Reference to user',
               existing_nullable=False)
    op.alter_column('user_events', 'event_id',
               existing_type=sa.INTEGER(),
               comment='Reference to event',
               existing_nullable=False)
    op.alter_column('user_events', 'attended_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Ticket purchase timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_events', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email associated with ticket',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_events', 'qrcode_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment='QR code image URL',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_events', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment='Unique verification token for entry',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index('idx_user_event_email', 'user_events', ['email'], unique=False)
    op.create_index('idx_user_event_event_id', 'user_events', ['event_id'], unique=False)
    op.create_index('idx_user_event_token', 'user_events', ['token'], unique=False)
    op.create_index('idx_user_event_user_id', 'user_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_events_email'), 'user_events', ['email'], unique=False)
    op.create_index(op.f('ix_user_events_event_id'), 'user_events', ['event_id'], unique=False)

    # Deduplicate token
    op.execute("""
        UPDATE user_events SET token = token || '_' || id
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY token ORDER BY id) as rn
                FROM user_events WHERE token IS NOT NULL
            ) t WHERE rn > 1
        )
    """)

    op.create_index(op.f('ix_user_events_token'), 'user_events', ['token'], unique=True)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    # Clean up orphans before adding FK
    op.execute("DELETE FROM user_events WHERE event_id NOT IN (SELECT id FROM eventcreation)")
    op.execute("DELETE FROM user_events WHERE user_id NOT IN (SELECT id FROM user_credential)")
    op.create_foreign_key(None, 'user_events', 'eventcreation', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_events', 'user_credential', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_events', 'isverified')
    op.drop_column('user_events', 'type')
    # Safely handle id column and primary key for user_interests
    op.execute("""
        DO $$
        BEGIN
            -- Add id column if it doesn't exist
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='user_interests' AND column_name='id') THEN
                ALTER TABLE user_interests ADD COLUMN id SERIAL PRIMARY KEY;
            END IF;
        END $$;
    """)
    op.execute("ALTER TABLE user_interests ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("ALTER TABLE user_interests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("COMMENT ON COLUMN user_interests.id IS 'User interest record unique identifier'")
    op.execute("COMMENT ON COLUMN user_interests.created_at IS 'Record creation timestamp'")
    op.execute("COMMENT ON COLUMN user_interests.updated_at IS 'Last update timestamp'")
    op.execute("ALTER TABLE user_interests ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE user_interests ALTER COLUMN updated_at DROP DEFAULT")
    op.alter_column('user_interests', 'user_id',
               existing_type=sa.INTEGER(),
               comment='Reference to user',
               existing_nullable=False)
    op.alter_column('user_interests', 'interests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='List of interest categories as JSON array',
               existing_nullable=False)
    # Deduplicate user_interests
    op.execute("""
        DELETE FROM user_interests
        WHERE id NOT IN (
            SELECT MAX(id) FROM user_interests GROUP BY user_id
        )
    """)

    op.create_index('idx_user_interests_user_id', 'user_interests', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_interests_user_id'), 'user_interests', ['user_id'], unique=True)
    # Clean up orphans before adding FK
    op.execute("DELETE FROM user_interests WHERE user_id NOT IN (SELECT id FROM user_credential)")
    op.create_foreign_key(None, 'user_interests', 'user_credential', ['user_id'], ['id'], ondelete='CASCADE')
    op.execute("ALTER TABLE userprofiles ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(500)")
    op.execute("ALTER TABLE userprofiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("ALTER TABLE userprofiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL")
    op.execute("COMMENT ON COLUMN userprofiles.profile_picture IS 'URL to profile picture'")
    op.execute("COMMENT ON COLUMN userprofiles.created_at IS 'Profile creation timestamp'")
    op.execute("COMMENT ON COLUMN userprofiles.updated_at IS 'Last update timestamp'")
    op.execute("ALTER TABLE userprofiles ALTER COLUMN created_at DROP DEFAULT")
    op.execute("ALTER TABLE userprofiles ALTER COLUMN updated_at DROP DEFAULT")
    op.alter_column('userprofiles', 'id',
               existing_type=sa.INTEGER(),
               comment='User profile unique identifier',
               existing_nullable=False,
               autoincrement=True)
    # Clean up non-numeric user_ids before casting
    op.execute("DELETE FROM userprofiles WHERE user_id !~ '^[0-9]+$'")
    op.alter_column('userprofiles', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               comment='Reference to user_credential',
               existing_nullable=False,
               postgresql_using='user_id::integer')
    op.alter_column('userprofiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="User's full name",
               existing_nullable=False)
    op.alter_column('userprofiles', 'phoneno',
               existing_type=sa.VARCHAR(length=255),
               comment="User's contact phone number",
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('userprofiles', 'address',
                existing_type=sa.TEXT(),
                existing_nullable=True)
    op.alter_column('userprofiles', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment="User's email address",
               existing_nullable=False)
    op.create_index('idx_user_profile_email', 'userprofiles', ['email'], unique=False)
    op.create_index('idx_user_profile_name', 'userprofiles', ['name'], unique=False)
    op.create_index('idx_user_profile_user_id', 'userprofiles', ['user_id'], unique=False)

    # Deduplicate userprofiles email
    op.execute("""
        UPDATE userprofiles SET email = email || '_' || id
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (PARTITION BY email ORDER BY id) as rn
                FROM userprofiles WHERE email IS NOT NULL
            ) t WHERE rn > 1
        )
    """)

    op.create_index(op.f('ix_userprofiles_email'), 'userprofiles', ['email'], unique=True)
    op.create_index(op.f('ix_userprofiles_user_id'), 'userprofiles', ['user_id'], unique=True)
    # Clean up orphans before adding FK
    op.execute("DELETE FROM userprofiles WHERE user_id NOT IN (SELECT id FROM user_credential)")
    op.create_foreign_key(None, 'userprofiles', 'user_credential', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofiles', type_='foreignkey')
    op.drop_index(op.f('ix_userprofiles_user_id'), table_name='userprofiles')
    op.drop_index(op.f('ix_userprofiles_email'), table_name='userprofiles')
    op.drop_index('idx_user_profile_user_id', table_name='userprofiles')
    op.drop_index('idx_user_profile_email', table_name='userprofiles')
    op.alter_column('userprofiles', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's email address",
               existing_nullable=False)
    op.alter_column('userprofiles', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="User's physical address",
               existing_nullable=True)
    op.alter_column('userprofiles', 'phoneno',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's contact phone number",
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('userprofiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="User's full name",
               existing_nullable=False)
    op.alter_column('userprofiles', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference to user_credential',
               existing_nullable=False)
    op.alter_column('userprofiles', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User profile unique identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('userprofiles', 'updated_at')
    op.drop_column('userprofiles', 'created_at')
    op.drop_column('userprofiles', 'profile_picture')
    op.drop_constraint(None, 'user_interests', type_='foreignkey')
    op.drop_index(op.f('ix_user_interests_user_id'), table_name='user_interests')
    op.drop_index('idx_user_interests_user_id', table_name='user_interests')
    op.alter_column('user_interests', 'interests',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of interest categories as JSON array',
               existing_nullable=False)
    op.alter_column('user_interests', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to user',
               existing_nullable=False)
    op.drop_column('user_interests', 'updated_at')
    op.drop_column('user_interests', 'created_at')
    op.drop_column('user_interests', 'id')
    op.add_column('user_events', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_events', sa.Column('isverified', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_token'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_email'), table_name='user_events')
    op.drop_index('idx_user_event_user_id', table_name='user_events')
    op.drop_index('idx_user_event_token', table_name='user_events')
    op.drop_index('idx_user_event_event_id', table_name='user_events')
    op.drop_index('idx_user_event_email', table_name='user_events')
    op.alter_column('user_events', 'token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique verification token for entry',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_events', 'qrcode_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='QR code image URL',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_events', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email associated with ticket',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_events', 'attended_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Ticket purchase timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_events', 'event_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to event',
               existing_nullable=False)
    op.alter_column('user_events', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to user',
               existing_nullable=False)
    op.drop_column('user_events', 'created_at')
    op.drop_column('user_events', 'verified_at')
    op.drop_column('user_events', 'isVerified')
    op.drop_column('user_events', 'ticket_type')
    op.drop_column('user_events', 'id')
    op.drop_index(op.f('ix_user_credential_username'), table_name='user_credential')
    op.drop_index(op.f('ix_user_credential_email'), table_name='user_credential')
    op.drop_index('idx_username', table_name='user_credential')
    op.drop_index('idx_email', table_name='user_credential')
    op.alter_column('user_credential', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Hashed password using bcrypt',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_credential', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Unique email address',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_credential', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Unique username for login',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('user_credential', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Unique user identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user_credential', 'is_active')
    op.drop_column('user_credential', 'updated_at')
    op.drop_column('user_credential', 'created_at')
    op.add_column('table_categories', sa.Column('event_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'table_categories', type_='foreignkey')
    op.drop_index(op.f('ix_table_categories_event_id'), table_name='table_categories')
    op.drop_index('idx_table_name', table_name='table_categories')
    op.drop_index('idx_table_event_id', table_name='table_categories')
    op.alter_column('table_categories', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Price per table',
               existing_nullable=False)
    op.alter_column('table_categories', 'capacity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of seats at this table',
               existing_nullable=False)
    op.alter_column('table_categories', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Table category name (e.g., Standard, VIP)',
               existing_nullable=False)
    op.alter_column('table_categories', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Table category unique identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('table_categories', 'updated_at')
    op.drop_column('table_categories', 'created_at')
    op.drop_column('table_categories', 'available_tables')
    op.drop_column('table_categories', 'event_id')
    op.drop_constraint(None, 'eventcreation', type_='foreignkey')
    op.drop_index(op.f('ix_eventcreation_event_name'), table_name='eventcreation')
    op.drop_index(op.f('ix_eventcreation_date'), table_name='eventcreation')
    op.drop_index(op.f('ix_eventcreation_creator_id'), table_name='eventcreation')
    op.drop_index(op.f('ix_eventcreation_category'), table_name='eventcreation')
    op.drop_index('idx_event_name', table_name='eventcreation')
    op.drop_index('idx_event_date', table_name='eventcreation')
    op.drop_index('idx_event_creator_id', table_name='eventcreation')
    op.drop_index('idx_event_category', table_name='eventcreation')
    op.alter_column('eventcreation', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='Event availability status',
               existing_server_default=sa.text('true'))
    op.alter_column('eventcreation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Last update timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('eventcreation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               comment=None,
               existing_comment='Event creation timestamp',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('eventcreation', 'table_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Table reservation price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'vvvip_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='VVVIP ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'vvip_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='VVIP ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'vip_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='VIP ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'bank',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bank name',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'account_number',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bank account number',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'account_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bank account holder name',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'date',
               existing_type=sa.DATE(),
               nullable=True,
               comment=None,
               existing_comment='Event date')
    op.alter_column('eventcreation', 'category',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Event category (concert, conference, etc)',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Regular ticket price',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('eventcreation', 'picture',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='Path to event promotional image',
               existing_nullable=True)
    op.alter_column('eventcreation', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Event description and details',
               existing_nullable=True)
    op.alter_column('eventcreation', 'time_out',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Event end time',
               existing_nullable=True)
    op.alter_column('eventcreation', 'time_in',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Event start time',
               existing_nullable=True)
    op.alter_column('eventcreation', 'event_address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Event venue address',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'event_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment=None,
               existing_comment='Event title/name',
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'brand_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Brand organizing the event',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('eventcreation', 'creator_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Reference to creator profile',
               existing_nullable=True)
    op.alter_column('eventcreation', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Event unique identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'creatorprofile', type_='foreignkey')
    op.drop_index(op.f('ix_creatorprofile_user_id'), table_name='creatorprofile')
    op.drop_index(op.f('ix_creatorprofile_email'), table_name='creatorprofile')
    op.drop_index(op.f('ix_creatorprofile_brandname'), table_name='creatorprofile')
    op.drop_index('idx_creator_user_id', table_name='creatorprofile')
    op.drop_index('idx_creator_email', table_name='creatorprofile')
    op.drop_index('idx_creator_brandname', table_name='creatorprofile')
    op.alter_column('creatorprofile', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Creator's email address",
               existing_nullable=False)
    op.alter_column('creatorprofile', 'brandname',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Brand or organization name',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('creatorprofile', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Creator's physical address",
               existing_nullable=True)
    op.alter_column('creatorprofile', 'phoneno',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Creator's contact phone number",
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('creatorprofile', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Creator's full name",
               existing_nullable=False)
    op.alter_column('creatorprofile', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Reference to user_credential',
               existing_nullable=False)
    op.alter_column('creatorprofile', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Creator profile unique identifier',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('creatorprofile', 'updated_at')
    op.drop_column('creatorprofile', 'created_at')
    op.drop_column('creatorprofile', 'profile_picture')
    op.drop_column('creatorprofile', 'bio')
    # ### end Alembic commands ###
